"""Regenerate data/activity.js from the git history of the projects the site shows.

The roadmap section of the site is "live" only in the sense that this script is re-run:
it reads each repository's log (all branches, no merge commits) and writes weekly commit
counts plus the most recent changes. Nothing is typed in by hand, nothing is fetched from
the network.

    python3 scripts/sync_activity.py
"""

import datetime as dt
import json
import subprocess
from pathlib import Path

DEV = Path.home() / "Dev"
OUT = Path(__file__).resolve().parent.parent / "data" / "activity.js"

# Order is the order of the lanes on the page.
REPOS = [
    {"key": "frugal_ml", "path": DEV / "projects/frugal_ml"},
    {"key": "ferrite-embedded", "path": DEV / "projects/ferrite-embedded"},
    {"key": "directConv", "path": DEV / "tinys/directConv"},
    {"key": "adalineDemo", "path": DEV / "tinys/adalineDemo"},
    {"key": "sentinel", "path": DEV / "projects/sentinel"},
    {"key": "Classifhear", "path": DEV / "tinys/Classifhear"},
]

START = dt.date(2026, 3, 30)  # Monday of the week frugal_ml's first commit falls in
RECENT = 12
# Formatting-only commits are counted in the weekly totals but kept out of the change log.
NOISE = ("rustfmt", "Format CI")


def log(path: Path) -> list[tuple[dt.date, str]]:
    out = subprocess.run(
        ["git", "-C", str(path), "log", "--all", "--no-merges", "--format=%H|%ad|%s", "--date=short"],
        capture_output=True, text=True, check=True,
    ).stdout
    seen, rows = set(), []
    for line in out.splitlines():
        sha, date, subject = line.split("|", 2)
        if sha in seen:
            continue
        seen.add(sha)
        rows.append((dt.date.fromisoformat(date), subject))
    return rows


def main() -> None:
    today = dt.date.today()
    n_weeks = (today - START).days // 7 + 1
    lanes, recent = [], []
    for repo in REPOS:
        rows = log(repo["path"])
        weeks = [0] * n_weeks
        for date, _ in rows:
            i = (date - START).days // 7
            if 0 <= i < n_weeks:
                weeks[i] += 1
        dates = [d for d, _ in rows]
        lanes.append({
            "key": repo["key"],
            "commits": len(rows),
            "first": min(dates).isoformat() if dates else None,
            "last": max(dates).isoformat() if dates else None,
            "weeks": weeks,
        })
        recent += [{"date": d.isoformat(), "repo": repo["key"], "msg": s}
                   for d, s in rows if not any(k in s for k in NOISE)]

    recent.sort(key=lambda r: r["date"], reverse=True)
    data = {
        "synced": today.isoformat(),
        "weekStart": START.isoformat(),
        "lanes": lanes,
        "recent": recent[:RECENT],
    }
    OUT.write_text("// Generated by scripts/sync_activity.py. Do not edit by hand.\n"
                   f"window.ACTIVITY = {json.dumps(data, ensure_ascii=False)};\n")
    print(f"wrote {OUT} ({sum(l['commits'] for l in lanes)} commits, {n_weeks} weeks)")


if __name__ == "__main__":
    main()
